module.exports = {
	extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'prettier'],
	rules: {
		'@typescript-eslint/ban-ts-comment': 'error',
		'@typescript-eslint/no-empty-function': 'error',
		'@typescript-eslint/no-explicit-any': 'error',
		'@typescript-eslint/no-invalid-this': ['error'],
		'@typescript-eslint/no-non-null-assertion': 'error',
		'@typescript-eslint/no-unused-expressions': ['error', { enforceForJSX: true }],
		'@typescript-eslint/no-unused-vars': ['error', { caughtErrorsIgnorePattern: '^_', argsIgnorePattern: '^_' }],
		'@typescript-eslint/no-use-before-define': ['error', { functions: false }],
		'@typescript-eslint/prefer-ts-expect-error': 'error',
		'array-callback-return': ['error'],
		'func-name-matching': ['error'],
		'new-cap': ['error'],
		'no-alert': 'error',
		'no-array-constructor': ['error'],
		'no-bitwise': ['error'],
		'no-caller': ['error'],
		'no-console': 'error',
		'no-constructor-return': ['error'],
		'no-duplicate-imports': ['error'],
		'no-eval': ['error'],
		'no-extend-native': ['error'],
		'no-extra-boolean-cast': ['error'],
		'no-floating-decimal': ['error'],
		'no-implied-eval': ['error'],
		'no-iterator': ['error'],
		'no-labels': ['error'],
		'no-lone-blocks': ['error'],
		'no-multi-assign': ['error'],
		'no-new-func': ['error'],
		'no-new-object': ['error'],
		'no-new-wrappers': ['error'],
		'no-new': ['error'],
		'no-promise-executor-return': ['error'],
		'no-proto': ['error'],
		'no-script-url': ['error'],
		'no-self-compare': ['error'],
		'no-throw-literal': ['error'],
		'no-unmodified-loop-condition': ['error'],
		'no-unreachable-loop': ['error'],
		'no-useless-call': ['error'],
		'no-useless-catch': ['error'],
		'no-useless-computed-key': ['error'],
		'no-useless-concat': ['error'],
		'no-useless-constructor': ['error'],
		'no-useless-rename': ['error'],
		'no-useless-return': ['error'],
		'no-var': ['error'],
		'no-warning-comments': ['error', { terms: ['todo', 'hack'] }],
		'object-shorthand': ['error'],
		'prefer-exponentiation-operator': ['error'],
		'prefer-object-spread': ['error'],
		'prefer-promise-reject-errors': ['error'],
		'prefer-rest-params': ['error'],
		'prefer-spread': ['error'],
		'symbol-description': ['error'],
		eqeqeq: ['error', 'always', { null: 'ignore' }],
	},
};
